// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Try to load dotenv if available (optional for Docker environments)
try {
  require("dotenv/config");
} catch (e) {
  // dotenv not available, environment variables should be set directly
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
